#!/bin/sh

set -e

if [ -z "$1" ] ; then
	echo "Usage: $0 VERSION"
	echo "Example: $0 v0.2"
	exit 1
fi

VERSION=$1

ROOT=$(dirname $(dirname $0))
cd $ROOT

for os in linux darwin windows ; do
	for arch in amd64 ; do
		export GOOS=$os
		export GOARCH=$arch

		releasename="rabbitmq-dump-queue-$VERSION-$GOOS-$GOARCH"
		releasedir="release/$releasename"

		echo "Building: $releasedir"

		rm -rf bin
		scripts/build

		rm -rf $releasedir
		mkdir -p $releasedir
		mv bin/* $releasedir/
		cp README.md $releasedir/
		cp LICENSE $releasedir/

		if [ "$os" = "linux" ] ; then
			(cd release && tar czf $releasename.tgz $releasename)
		else
			(cd release && zip -qr $releasename.zip $releasename)
		fi
	done
done

echo "Done, see files in the 'release' directory."
echo
echo "Don't forget to tag:    git tag -a $VERSION -m 'Release $VERSION' && git push --tags"
